---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Effect of climate change, mountain pine beetle, and forest fires on carbon cycling in whitebark pine (*Pinus albicus*) stands

```{r packages_and_function, message=FALSE}
library(tidyverse)
library(sensitivity)
library(reshape2)
library(cowplot)
library(popbio)
library(rgdal)
library(raster)
library(deSolve)

source("../R/SubModel0_climate_variables.R") # Simulate climate change
source("../R/SubModel1_BarkBeetles.R") # Bark beetle growth
source("../R/SubModel2_PineModel.R") # Whitebark pine matrix projection model
source("../R/SubModel3_Fire.R") # Fire model
source("../R/Submodel5_calc_biomass_carbon.R") # whitebark pine carbon and biomass model
source("../R/wrapper_function.R")
options(scipen = 999)
```


####Setting up climate change data
```{r read_climate_data, message=FALSE, warning=TRUE, paged.print=TRUE}
# Find average tmin and tmax values for Sierra Nevada Ecoregion based on historic data
cwd_raw = raster("../climate_data/cwd1981_2010_ave_HST_1559416632/cwd1981_2010_ave_HST_1559416632.tif")
snwpck_raw = raster("../climate_data/aprpck1981_2010_ave_HST_1559416720/aprpck1981_2010_ave_HST_1559416720.tif")
W_tmin_raw = raster("../climate_data/tmn1981_2010djf_ave_HST_1559415579/tmn1981_2010djf_ave_HST_1559415579.tif")
Su_tmax_raw = raster("../climate_data/tmx1981_2010jja_ave_HST_1559415851/tmx1981_2010jja_ave_HST_1559415851.tif")
crop_layer = readOGR("../climate_data/SNC_Boundary_Shapefile/SNC_Boundary.shp")
```

#### ############## Business-as-usual Climate Change ###################

#### Find historic averages for climate variables of interest
```{r gen_input_clim_data}
# Initialize climate data.frame
clim_BAU = data.frame(year = 2010:2100)

# Fill in climate data table
clim_parms = list(total_change=-50,time=nrow(clim_BAU)) # April snowpack reduced by ~50%
clim_BAU$apr_snow = climate_variables_fun(snwpck_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=400,time=nrow(clim_BAU)) # CWD increases ~400 mm
clim_BAU$cwd = climate_variables_fun(cwd_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=nrow(clim_BAU)) # Winter minimum temp increases 10 degrees C
clim_BAU$W_tmin = climate_variables_fun(W_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=nrow(clim_BAU)) # Maximum summer temp increases 10 degrees C
clim_BAU$Su_tmax = climate_variables_fun(Su_tmax_raw,crop_layer = crop_layer,parms = clim_parms)
```


```{r beetles_only}
impact_type = "beetles_only"
climate_chng_scen = "business-as-usual"

# Pine Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742
F3 = 0.2536 
F4 = 1.6902

# Pine Survival
p0 = 0.9353
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959

# Pine Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144

beetle_K = 500000
scenario_parms = list(years = length(clim_BAU),
                      time_step=2)

beetle_parms = list(btl_pop_0=5000, 
                    r_max=1.16, 
                    K_0_btl = beetle_K)

pine_parms = list(ntrees_0 = 1000,
                  initial_pop = c(100,100,50,50,50),
                  initial_carbon = 0,
                  stages = c("<1cm","1-10cm","10-20cm","20-40cm",">40cm"),
                  avg_stage_dbh = c(1,5,15,30,50),
                  pine_fert = c(F0,F1,F2,F3,F4),
                  pine_surv = c(p0,p1,p2,p3,p4),
                  pine_growth = c(g01,g12,g23,g34))

beetles_only = whitePine_PopDynamics_model(clim_df = clim_BAU,
                                clim_scen_name = climate_chng_scen,
                                impact_type = impact_type,
                                scenario_parms = scenario_parms,
                                pine_parms = pine_parms,
                                beetle_parms = beetle_parms,
                                beetle_K = beetle_K)
```

```{r climate_only}
impact_type = "climate_only"
climate_chng_scen = "business-as-usual"

# Pine Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742
F3 = 0.2536 
F4 = 1.6902

# Pine Survival
p0 = 0.9353
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959

# Pine Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144

scenario_parms = list(years = length(clim_BAU),
                      time_step=2)

beetle_parms = list(btl_pop_0=5000, 
                    r_max=1.16, 
                    K_0_btl = 500000)

pine_parms = list(ntrees_0 = 1000,
                  initial_pop = c(100,100,50,50,50),
                  initial_carbon = 0,
                  stages = c("<1cm","1-10cm","10-20cm","20-40cm",">40cm"),
                  avg_stage_dbh = c(1,5,15,30,50),
                  pine_fert = c(F0,F1,F2,F3,F4),
                  pine_surv = c(p0,p1,p2,p3,p4),
                  pine_growth = c(g01,g12,g23,g34))

climate_only = whitePine_PopDynamics_model(clim_df = clim_BAU,
                                clim_scen_name = climate_chng_scen,
                                impact_type = impact_type,
                                scenario_parms = scenario_parms,
                                pine_parms = pine_parms,
                                beetle_parms = beetle_parms,
                                beetle_K = beetle_K)
```


```{r beetles_and_climate}
impact_type = "beetles_and_climate"
climate_chng_scen = "business-as-usual"

# Pine Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742
F3 = 0.2536 
F4 = 1.6902

# Pine Survival
p0 = 0.9353
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959

# Pine Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144

scenario_parms = list(years = length(clim_BAU),
                      time_step=2)

beetle_parms = list(btl_pop_0=5000, 
                    r_max=1.16, 
                    K_0_btl = 50000)

pine_parms = list(ntrees_0 = 1000,
                  initial_pop = c(100,100,50,50,50),
                  initial_carbon = 0,
                  stages = c("<1cm","1-10cm","10-20cm","20-40cm",">40cm"),
                  avg_stage_dbh = c(1,5,15,30,50),
                  pine_fert = c(F0,F1,F2,F3,F4),
                  pine_surv = c(p0,p1,p2,p3,p4),
                  pine_growth = c(g01,g12,g23,g34))

beetles_and_climate = whitePine_PopDynamics_model(clim_df = clim_BAU,
                                clim_scen_name = climate_chng_scen,
                                impact_type = impact_type,
                                scenario_parms = scenario_parms,
                                pine_parms = pine_parms,
                                beetle_parms = beetle_parms,
                                beetle_K = beetle_K)
```


##Graph Results:
```{r}

scenario_df = rbind.data.frame(climate_only, beetles_only, beetles_and_climate)

ggplot(scenario_df %>% filter(climate == "business-as-usual"), 
       aes(x = year, y = postFire_forest_carbon, by = impact_type))+
  facet_wrap(~impact_type)+
  geom_line()+
  xlab("Year")+
  ylab("Carbon in Forest (kg)")+
  ggtitle("Climate Scenario: Business As Usual")
  #scale_colour_discrete(name = "Forest impacted by:",
  #                      labels = c("Climate", "Beetles", "Climate & Beetles"))


```

