---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Effect of climate change, mountain pine beetle, and forest fires on carbon cycling in whitebark pine (*Pinus albicus*) stands

```{r packages_and_function, message=FALSE}
library(tidyverse)
library(sensitivity)
library(reshape2)
library(cowplot)
library(popbio)
library(rgdal)
library(raster)
library(deSolve)

source("../R/SubModel0_climate_variables.R") # Simulate climate change
source("../R/SubModel1_BarkBeetles.R") # Bark beetle growth
source("../R/SubModel2_PineModel.R") # Whitebark pine matrix projection model
source("../R/SubModel3_Fire.R") # Fire model
source("../R/Submodel5_calc_biomass_carbon.R") # whitebark pine carbon and biomass model
source("../R/wrapper_function.R")
options(scipen = 999)
```

```{r read_climate_data, message=FALSE, warning=TRUE, paged.print=TRUE}
# Find average tmin and tmax values for Sierra Nevada Ecoregion based on historic data
cwd_raw = raster("../climate_data/cwd1981_2010_ave_HST_1559416632/cwd1981_2010_ave_HST_1559416632.tif")
snwpck_raw = raster("../climate_data/aprpck1981_2010_ave_HST_1559416720/aprpck1981_2010_ave_HST_1559416720.tif")
W_tmin_raw = raster("../climate_data/tmn1981_2010djf_ave_HST_1559415579/tmn1981_2010djf_ave_HST_1559415579.tif")
Su_tmax_raw = raster("../climate_data/tmx1981_2010jja_ave_HST_1559415851/tmx1981_2010jja_ave_HST_1559415851.tif")
crop_layer = readOGR("../climate_data/SNC_Boundary_Shapefile/SNC_Boundary.shp")
```

#### ############## Business-as-usual Climate Change ###################

#### Find historic averages for climate variables of interest
```{r gen_input_clim_data}
# Initialize climate data.frame
clim_BAU = data.frame(year = 2010:2100)

# Fill in climate data table
clim_parms = list(total_change=-50,time=nrow(clim_BAU)) # April snowpack reduced by ~50%
clim_BAU$apr_snow = climate_variables_fun(snwpck_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=400,time=nrow(clim_BAU)) # CWD increases ~400 mm
clim_BAU$cwd = climate_variables_fun(cwd_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=nrow(clim_BAU)) # Winter minimum temp increases 10 degrees C
clim_BAU$W_tmin = climate_variables_fun(W_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=nrow(clim_BAU)) # Maximum summer temp increases 10 degrees C
clim_BAU$Su_tmax = climate_variables_fun(Su_tmax_raw,crop_layer = crop_layer,parms = clim_parms)
```


# Setting model inputs
```{r climate_BAU}
#### Scenario length and name ####
impact = "beetles"
climate = "BAU"

# Pine Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742
F3 = 0.2536 
F4 = 1.6902

# Pine Survival
p0 = 0.9353
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959

# Pine Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144

scenario_parms = list(years = length(clim_BAU),
                      clim_coef = clim_BAU$cwd[1]/clim_BAU$cwd,
                      time_step=2)

beetle_parms = list(btl_coef = (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1),
                    btl_pop_0=5000, 
                    r_max_0=1.16, 
                    K_0_btl = 5000)

pine_parms = list(ntrees_0 = 1000,
                  initial_pop = c(200,200,200,200,200),
                  initial_carbon = 0,
                  stages = c("<1cm","1-10cm","10-20cm","20-40cm",">40cm"),
                  pine_fert = c(F0,F1,F2,F3,F4),
                  pine_surv = c(p0,p1,p2,p3,p4),
                  pine_growth = c(g01,g12,g23,g34))

a = whitePine_PopDynamics_model(clim_df = clim_BAU,clim_scen_name = "BAU",scenario_parms = scenario_parms,pine_parms = pine_parms,beetle_parms = beetle_parms)
```


```{r}




```



```{r beetle}



combined = data.frame(year = 2010:2100,
                      btl_r_coef = ifelse((log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)<1,1,
                                          (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)),
                      btl_r = rep(NA,91),
                      btl_pop = rep(NA,91),
                      p_p0 = c(p0*clim_coef), # Climate impact
                      p_p1 = rep(p1, 91),
                      p_p2 = rep(p2, 91),
                      p_p3 = rep(NA, 91), # Beetle impact (in for loop)
                      p_p4 = rep(NA, 91), # Beetle impact (in for loop) 
                      g01 = c(g01*clim_coef), # Climate impact
                      g12 = c(g12*clim_coef), # Climate impact
                      g23 = c(g23*clim_coef), # Climate impact
                      g34 = c(g34*clim_coef), # Climate impact
                      pine0 = rep(NA,91),
                      pine1 = rep(NA,91),
                      pine2 = rep(NA,91), 
                      pine3 = rep(NA,91), 
                      pine4 = rep(NA,91),
                      total_pine = rep(0,91),
                      forest_carbon = rep(0,91),
                      fire_prob = rep(NA,years), # Fire probability, binary (High/Low)
                      fire_sev = rep(NA,years), # Fire severity, (Low, Moderate, Severe)
                      impact = rep(impact, years),
                      climate = rep(climate, years))

combined[,3] = round(r_0*combined$btl_r_coef,2)
combined[1,4] = btl_pop_0
combined[1,5:9] = pine_surv
combined[1,14:18] = c(107,77,300,14,1)
combined[1,19] = sum(combined[1,14:18])
combined[1,20] = 256876
combined[1,21] = ifelse(clim_BAU$Su_tmax[1] >36 && clim_BAU$W_tmin[1] > 2, "H", "L") 
combined[1,22] = ifelse(clim_BAU$apr_snow[1] >=80, "Low", ifelse(clim_BAU$apr_snow[1] >=60, "Mod", "Sev")) 


for(i in 2:years){
################################################# Fire ######################

combined$fire_prob[i] = ifelse(clim_BAU$Su_tmax[i] >36 && clim_BAU$W_tmin[i] > 2, "H", "L")
fire_prob = combined$fire_prob[i]
combined$fire_sev[i] =  ifelse(clim_BAU$apr_snow[i] >=80, "Low", ifelse(clim_BAU$apr_snow[i] >=60, "Mod", "Sev"))
fire_sev = combined$fire_sev[i]

################################################# Beetles ######################

  tmp = data.frame(time = 1:time)
  Ki = K_0*combined$total_pine[i-1]/combined$total_pine[1]
  beetle_parms = list(p0=btl_pop_0, r=r_0, K=Ki)
  tmp_result = ode(combined$btl_pop[i-1], tmp$time, beetle_pop, beetle_parms)
  combined$btl_pop[i] = clim_coef * tmp_result[2,2]

################################################# Pines ######################
  
  pine_surv = as.numeric(combined[i-1,5:9])
  pine_growth = as.numeric(combined[i-1,10:13])
  init_pop = as.numeric(combined[i-1,14:18])
  combined$p_p3[i] = combined$p_p3[i-1]*log(combined$btl_pop[1])/log(combined$btl_pop[i]) # This calculates a survival value based on the size of the beetle population. As the beetle pop grows, survival decreases. 
  combined$p_p4[i] = combined$p_p4[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  
  pine_fire = whitePine_matrix_FIREmodel(fertility = pine_fert,
                                survival = pine_surv,
                                growth = pine_growth,
                                fire_prob = fire_prob,
                                fire_sev = fire_sev,
                                time = 2,
                                initial_pop = ntrees_0)
  
  pine_pop = pine_fire[[1]]
  combined[i,14:18] = pine_pop[,2]
  combined[i,19] = sum(combined[i,14:18])
  
  frst_crbn = pine_fire[[4]]
  combined[i,20] = frst_crbn[2]
  
}

#Scenario specific vector
beetle = combined$forest_carbon

#Add to overarching dataframe
scenario_df = rbind.data.frame(scenario_df, combined)

```



