---
title: "MainModel_Short_ForestCarbonSeq"
author: "Claire Powers & Emma Mendonsa"
date: "June 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages_and_function, message=FALSE}
library(tidyverse)
library(sensitivity)
library(reshape2)
library(cowplot)
library(popbio)
library(rgdal)
library(raster)
library(deSolve)

source("../R/Scenario_Function.R")
source("../R/SubModel0_climate_variables.R")
source("../R/SubModel1_BarkBeetles.R")
source("../R/SubModel4_PineModel-Fire_combo.R")

options(scipen = 999)
```


```{r read_climate_data}
# Find average tmin and tmax values for Sierra Nevada Ecoregion based on historic data
cwd_raw = raster("../climate_data/cwd1981_2010_ave_HST_1559416632/cwd1981_2010_ave_HST_1559416632.tif")
snwpck_raw = raster("../climate_data/aprpck1981_2010_ave_HST_1559416720/aprpck1981_2010_ave_HST_1559416720.tif")
W_tmin_raw = raster("../climate_data/tmn1981_2010djf_ave_HST_1559415579/tmn1981_2010djf_ave_HST_1559415579.tif")
Sp_tmin_raw = raster("../climate_data/tmn1981_2010mar_ave_HST_1559415612/tmn1981_2010mar_ave_HST_1559415612.tif")
F_tmin_raw = raster("../climate_data/tmn1981_2010nov_ave_HST_1559415731/tmn1981_2010nov_ave_HST_1559415731.tif")
Su_tmax_raw = raster("../climate_data/tmx1981_2010jja_ave_HST_1559415851/tmx1981_2010jja_ave_HST_1559415851.tif")
crop_layer = readOGR("../climate_data/SNC_Boundary_Shapefile/SNC_Boundary.shp")
```

###  ############## Business-as-usual Climate Change ######################

### Find historic averages for climate variables of interest
```{r generate_input_data}
years = 91
clim_BAU = data.frame(year = 2010:2100,
                      time = 1:91)

# Fill in climate data table
clim_parms = list(total_change=-50,time=years)
clim_BAU$apr_snow = climate_variables_fun(snwpck_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=400,time=years)
clim_BAU$cwd = climate_variables_fun(cwd_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=years)
clim_BAU$F_tmin = climate_variables_fun(F_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=years)
clim_BAU$Sp_tmin = climate_variables_fun(Sp_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=years)
clim_BAU$W_tmin = climate_variables_fun(W_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=10,time=years)
clim_BAU$Su_tmax = climate_variables_fun(Su_tmax_raw,crop_layer = crop_layer,parms = clim_parms)
```

# (Forest Carbon) Only effected by climate
```{r climate}

##Set Up inputs for Scenario Function:
climate_name = "BAU"
impact = "climate"
years = 91 # Total length of time
time = 2 # Number of timesteps used in for loop. 1 for the [i-1] and 2 for [i]

ntrees_0 = 1000
clim_df = clim_BAU
initial_carbon = 256876

r_0 = 1.16 # Initial r_max value for beetles
btl_pop_0 = 5000 # Initial size of beetle populatio
K_0 = 100000 # Starting carrying capacity for beetles
beetle_parms = list(p0=btl_pop_0, r=r_0, K=K_0) # list of beetle model input parameters

# Pine Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742
F3 = 0.2536 
F4 = 1.6902
# Pine Fertility vector to put into matrix
pine_fert = c(F0,F1,F2,F3,F4)

# Pine Survival
p0 = 0.9353
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959
# Pine Survival vector to put into matrix
pine_surv = c(p0,p1,p2,p3,p4)

# Pine Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144
# Pine Growth vector to put into matrix
pine_growth = c(g01,g12,g23,g34)


stages = c("<1cm","1-10cm","10-20cm","20-40cm",">40cm")
clim_coef = clim_BAU$cwd[1]/clim_BAU$cwd
btl_coef = log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1

BAU_climate_results = scenario_function(years, time, ntrees_0, initial_carbon = 256876, 
                                        r_0 = r_0, btl_pop_0, K_0, beetle_parms, 
                                        pine_fert, pine_surv, pine_growth, stages, 
                                        clim_coef, btl_coef, clim_df = clim_BAU)

BAU_climate_df = BAU_climate_results[[1]] # Pull out dataframe results

###Plot###
BAU_climate = BAU_climate_df$forest_carbon # Putting output of carbon into it's own dataframe to plot with others
BAU_climate_fire = BAU_climate_df$post_fire_carbon #to plot with others

```

# Only effected by beetles
```{r beetle}
years = 91
r_0 = 1.16
btl_pop_0 = 5000
ntrees_0 = 1000
time = 2
K_0 = 100000

beetle_parms = list(p0=btl_pop_0, r=r_0, K=K_0)

clim_coef = 1 # Equal to one becuase no climate impact here

pine_fert = c(F0,F1,F2,F3,F4)
pine_growth = c(g01,g12,g23,g34)
pine_surv = c(p0,p1,p2,p3,p4)

combined = data.frame(year = 2010:2100,
                      btl_r_coef = ifelse((log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)<1,1,
                      (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)),
                      btl_r = rep(NA,91),
                      btl_pop = rep(NA,91),
                      p_p0 = c(p0*clim_coef), # Climate impact
                      p_p1 = rep(p1, 91),
                      p_p2 = rep(p2, 91),
                      p_p3 = rep(NA, 91), # Beetle impact (in for loop)
                      p_p4 = rep(NA, 91), # Beetle impact (in for loop) 
                      g01 = c(g01*clim_coef), # Climate impact
                      g12 = c(g12*clim_coef), # Climate impact
                      g23 = c(g23*clim_coef), # Climate impact
                      g34 = c(g34*clim_coef), # Climate impact
                      pine0 = rep(NA,91),
                      pine1 = rep(NA,91),
                      pine2 = rep(NA,91), 
                      pine3 = rep(NA,91), 
                      pine4 = rep(NA,91),
                      total_pine = rep(0,91),
                      forest_carbon = rep(0,91),
                      fire_prob = rep(NA,91), # Fire probability, binary (High/Low)
                      fire_sev = rep(NA,91), # Fire severity, (Low, Moderate, Severe)
                      fire_occurs = rep(NA,91), # Fire occurs, binary (Y/N)
                      burnt_biomass = rep(0,91), # Total biomass burnt
                      post_fire_carbon = rep(0,91)) # Total forest carbon, post-fire)

combined[,3] = round(r_0*combined$btl_r_coef,2)
combined[1,4] = btl_pop_0
combined[1,5:9] = pine_surv
combined[1,14:18] = c(107,77,300,14,1)
combined[1,19] = sum(combined[1,14:18])
combined[1,20] = 256876
combined[1,21] = ifelse(clim_BAU$Su_tmax[1] >36 && clim_BAU$W_tmin[1] > 2, "H", "L") 
combined[1,22] = ifelse(clim_BAU$apr_snow[1] >=80, "Low", ifelse(clim_BAU$apr_snow[1] >=60, "Mod", "Sev")) 
combined[1,23] = ifelse(combined$fire_prob[1] == "H" && combined$fire_sev[1] == "Mod" |
                          combined$fire_sev[1] == "Sev", "Y", "N")
combined[1,24] = 0 
combined[1,25] = 256876

for(i in 2:years){
################################################# Fire ######################
combined$fire_prob[i] = ifelse(clim_BAU$Su_tmax[i] >36 && clim_BAU$W_tmin[i] > 2, "H", "L")
combined$fire_sev[i] =  ifelse(clim_BAU$apr_snow[i] >=80, "Low", ifelse(clim_BAU$apr_snow[i] >=60, "Mod", "Sev"))
combined$fire_occurs[i] = ifelse(combined$fire_prob[i] == "H" && combined$fire_sev[i] == "Mod"
                                 |combined$fire_sev[i] == "Sev", "Y", "N")

################################################# Beetles ######################

  tmp = data.frame(time = 1:time)
  tmp_result = ode(combined$btl_pop[i-1], tmp$time, beetle_pop, beetle_parms)
  combined$btl_pop[i] = clim_coef * tmp_result[2,2]

################################################# Pines ######################
  
  pine_surv = as.numeric(combined[i-1,5:9])
  pine_growth = as.numeric(combined[i-1,10:13])
  init_pop = as.numeric(combined[i-1,14:18])
  combined$p_p3[i] = combined$p_p3[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i]) # This calculates a survival value based on the size of the beetle population. As the beetle pop grows, survival decreases. 
  combined$p_p4[i] = combined$p_p4[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  
  pine = whitePine_matrix_model(fertility = pine_fert,
                                survival = pine_surv,
                                growth = pine_growth,
                                time = 2,
                                initial_pop = ntrees_0)
  
  pine_pop = pine[[1]]
  combined[i,14:18] = pine_pop[,2]
  combined[i,19] = sum(combined[i,14:18])
  
  frst_crbn = pine[[4]]
  combined[i,20] = frst_crbn[2]
  
  pine_biomass = pine[[3]] # Pull out biomass across stages
  combined$burnt_biomass[i] = ifelse(combined$fire_occurs[i] == "Y" && 
                                    combined$fire_sev[i] == "Low", (sum(pine_biomass[1:3,2])*.3),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Mod", (sum(pine_biomass[1:4,2])*.51),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Sev", (sum(pine_biomass[1:5,2])*.8),
                      0)))
  combined$post_fire_carbon[i] = combined$forest_carbon[i] - (combined$burnt_biomass[i] * 0.47)
}

beetle = combined$forest_carbon
beetle_fire = combined$post_fire_carbon #to plot with others

```

# Effected by both
```{r climate_beetle}
clim_coef = clim_BAU$cwd[1]/clim_BAU$cwd
pine_surv = c(p0,p1,p2,p3,p4)

combined = data.frame(year = 2010:2100,
                       btl_r_coef = ifelse((log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)<1,1,
                                          (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)),
                      btl_r = rep(NA,91),
                      btl_pop = rep(NA,91),
                      p_p0 = c(p0*clim_coef), # Climate impact
                      p_p1 = rep(p1, 91),
                      p_p2 = rep(p2, 91),
                      p_p3 = rep(NA, 91), # Beetle impact (in for loop)
                      p_p4 = rep(NA, 91), # Beetle impact (in for loop) 
                      g01 = c(g01*clim_coef), # Climate impact
                      g12 = c(g12*clim_coef), # Climate impact
                      g23 = c(g23*clim_coef), # Climate impact
                      g34 = c(g34*clim_coef), # Climate impact
                      pine0 = rep(NA,91),
                      pine1 = rep(NA,91),
                      pine2 = rep(NA,91), 
                      pine3 = rep(NA,91), 
                      pine4 = rep(NA,91),
                      total_pine = rep(NA,91),
                      forest_carbon = rep(NA,91),
                      fire_prob = rep(NA,91), # Fire probability, binary (High/Low)
                      fire_sev = rep(NA,91), # Fire severity, (Low, Moderate, Severe)
                      fire_occurs = rep(NA,91), # Fire occurs, binary (Y/N)
                      burnt_biomass = rep(0,91), # Total biomass burnt
                      post_fire_carbon = rep(0,91)) # Total forest carbon, post-fire)

combined[,3] = round(r_0*combined$btl_r_coef,2)
combined[1,4] = btl_pop_0
combined[1,5:9] = pine_surv
combined[1,14:18] = c(107,77,300,14,1)
combined[1,19] = sum(combined[1,14:18])
combined[1,20] = 256876
combined[1,21] = ifelse(clim_BAU$Su_tmax[1] >36 && clim_BAU$W_tmin[1] > 2, "H", "L") 
combined[1,22] = ifelse(clim_BAU$apr_snow[1] >=80, "Low", ifelse(clim_BAU$apr_snow[1] >=60, "Mod", "Sev")) 
combined[1,23] = ifelse(combined$fire_prob[1] == "H" && combined$fire_sev[1] == "Mod" |
                          combined$fire_sev[1] == "Sev", "Y", "N")
combined[1,24] = 0 
combined[1,25] = 256876

for(i in 2:years){
  ################################################# Fire ######################
combined$fire_prob[i] = ifelse(clim_BAU$Su_tmax[i] >36 && clim_BAU$W_tmin[i] > 2, "H", "L")
combined$fire_sev[i] =  ifelse(clim_BAU$apr_snow[i] >=80, "Low", ifelse(clim_BAU$apr_snow[i] >=60, "Mod", "Sev"))
combined$fire_occurs[i] = ifelse(combined$fire_prob[i] == "H" && combined$fire_sev[i] == "Mod"
                                 |combined$fire_sev[i] == "Sev", "Y", "N")

################################################# Beetles ######################

  tmp = data.frame(time = 1:time)
  tmp_result = ode(combined$btl_pop[i-1], tmp$time, beetle_pop, beetle_parms)
  combined$btl_pop[i] = clim_coef[i] * tmp_result[2,2]

################################################# Pines ######################

  # Pines
  pine_surv = as.numeric(combined[i-1,5:9])
  pine_growth = as.numeric(combined[i-1,10:13])
  init_pop = as.numeric(combined[i-1,14:18])
  combined$p_p3[i] = combined$p_p3[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  combined$p_p4[i] = combined$p_p4[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  
  pine = whitePine_matrix_model(fertility = pine_fert,
                                survival = pine_surv,
                                growth = pine_growth,
                                time=2,
                                initial_pop = ntrees_0)
  
  pine_pop = pine[[1]]
  combined[i,14:18] = pine_pop[,2]
  combined[i,19] = sum(combined[i,14:18])
  
  frst_crbn = pine[[4]]
  combined[i,20] = frst_crbn[2]

  pine_biomass = pine[[3]] # Pull out biomass across stages
  combined$burnt_biomass[i] = ifelse(combined$fire_occurs[i] == "Y" && 
                                    combined$fire_sev[i] == "Low", (sum(pine_biomass[1:3,2])*.3),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Mod", (sum(pine_biomass[1:4,2])*.51),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Sev", (sum(pine_biomass[1:5,2])*.8),
                      0)))
  combined$post_fire_carbon[i] = combined$forest_carbon[i] - (combined$burnt_biomass[i] * 0.47)  
}

climate_and_beetle = combined$forest_carbon
climate_and_beetle_fire = combined$post_fire_carbon #to plot with others

```

# BAU Trends
```{r BAU_output_vis}
BAU_forest_carbon_df = cbind.data.frame(year = 2010:2100,
                                  beetle=beetle,
                                  climate=climate,
                                  climate_and_beetle=climate_and_beetle,
                                  beetle_fire,
                                  climate_fire,
                                  climate_and_beetle_fire) %>% 
 # filter(year != "2010"&year !="2011") %>% # weird things happening in these years. Excluding because not important to trends
   melt(1)

colnames(BAU_forest_carbon_df) = c("year","scenario","carbon")

bau_trends = ggplot(BAU_forest_carbon_df,aes(x=year,y=carbon))+
  geom_line(aes(color=scenario))
```


###  ############## Moderate Climate Change ######################
### Repeat with different climate change
```{r generate_input_data}

### Find historic averages for climate variables of interest and then create a theoretical climate change scenario based on those averages and expected change 
years = 91 
clim_moderate = data.frame(year = 2010:2100,
                      time = 1:91,
                      apr_snow = rep(NA,91),
                      cwd = rep(NA,91),
                      F_tmin = rep(NA,91),
                      W_tmin = rep(NA,91),
                      Sp_tmin = rep(NA,91),
                      Su_tmax = rep(NA,91))

# Fill in climate data table
clim_parms = list(total_change=-20,time=years)
clim_moderate$apr_snow = climate_variables_fun(snwpck_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=200,time=years)
clim_moderate$cwd = climate_variables_fun(cwd_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=5,time=years)
clim_moderate$F_tmin = climate_variables_fun(F_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=5,time=years)
clim_moderate$Sp_tmin = climate_variables_fun(Sp_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=5,time=years)
clim_moderate$W_tmin = climate_variables_fun(W_tmin_raw,crop_layer = crop_layer,parms = clim_parms)

clim_parms = list(total_change=5,time=years)
clim_moderate$Su_tmax = climate_variables_fun(Su_tmax_raw,crop_layer = crop_layer,parms = clim_parms)
```

### COMBINING BEETLE AND PINE MODELS
# Only effected by climate
```{r climate}
years = 91
r_0 = 1.16
btl_pop_0 = 5000
ntrees_0 = 1000
time = 2
K_0 = 100000

beetle_parms = list(p0=btl_pop_0, r=r_0, K=K_0)

# Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742
F3 = 0.2536 
F4 = 1.6902
# Fertility vector to put into matrix
pine_fert = c(F0,F1,F2,F3,F4)

# Survival
p0 = 0.9353
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959
# Survival vector to put into matrix
pine_surv = c(p0,p1,p2,p3,p4)

# Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144
# Growth vector to put into matrix
pine_growth = c(g01,g12,g23,g34)

stages = c("a","b","c","d","e")
clim_coef = clim_moderate$cwd[1]/clim_moderate$cwd

combined = data.frame(year = 2010:2100,
                      btl_r_coef = ifelse((log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)<1,1,
                                          (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)),
                      btl_r = rep(NA,91),
                      btl_pop = rep(NA,91),
                      p_p0 = c(p0*clim_coef), # Climate impact
                      p_p1 = rep(p1, 91),
                      p_p2 = rep(p2, 91),
                      p_p3 = rep(p3, 91), # No Beetle impact (in for loop)
                      p_p4 = rep(p4, 91), # No Beetle impact (in for loop) 
                      g01 = c(g01*clim_coef), # Climate impact
                      g12 = c(g12*clim_coef), # Climate impact
                      g23 = c(g23*clim_coef), # Climate impact
                      g34 = c(g34*clim_coef), # Climate impact
                      pine0 = rep(NA,91),
                      pine1 = rep(NA,91),
                      pine2 = rep(NA,91), 
                      pine3 = rep(NA,91), 
                      pine4 = rep(NA,91),
                      total_pine = rep(0,91),
                      forest_carbon = rep(0,91),
                      fire_prob = rep(NA,91), # Fire probability, binary (High/Low)
                      fire_sev = rep(NA,91), # Fire severity, (Low, Moderate, Severe)
                      fire_occurs = rep(NA,91), # Fire occurs, binary (Y/N)
                      burnt_biomass = rep(0,91), # Total biomass burnt
                      post_fire_carbon = rep(0,91)) # Total forest carbon, post-fire)

combined[,3] = round(r_0*combined$btl_r_coef,2)
combined[1,4] = btl_pop_0
combined[1,5:9] = pine_surv
combined[1,14:18] = c(107,77,300,14,1)
combined[1,19] = sum(combined[1,14:18])
combined[1,20] = 256876
combined[1,21] = ifelse(clim_BAU$Su_tmax[1] >36 && clim_BAU$W_tmin[1] > 2, "H", "L") 
combined[1,22] = ifelse(clim_BAU$apr_snow[1] >=80, "Low", ifelse(clim_BAU$apr_snow[1] >=60, "Mod", "Sev")) 
combined[1,23] = ifelse(combined$fire_prob[1] == "H" && combined$fire_sev[1] == "Mod" |
                          combined$fire_sev[1] == "Sev", "Y", "N")
combined[1,24] = 0 
combined[1,25] = 256876

for(i in 2:years){
################################################# Fire ######################
combined$fire_prob[i] = ifelse(clim_BAU$Su_tmax[i] >36 && clim_BAU$W_tmin[i] > 2, "H", "L")
combined$fire_sev[i] =  ifelse(clim_BAU$apr_snow[i] >=80, "Low", ifelse(clim_BAU$apr_snow[i] >=60, "Mod", "Sev"))
combined$fire_occurs[i] = ifelse(combined$fire_prob[i] == "H" && combined$fire_sev[i] == "Mod"
                                 |combined$fire_sev[i] == "Sev", "Y", "N")

################################################# Beetles ######################

  tmp = data.frame(time = 1:time)
  tmp_result = ode(combined$btl_pop[i-1], tmp$time, beetle_pop, beetle_parms)
  combined$btl_pop[i] = clim_coef[i] * tmp_result[2,2]

################################################# Pines ######################
  
  pine_surv = as.numeric(combined[i-1,5:9])
  pine_growth = as.numeric(combined[i-1,10:13])
  init_pop = as.numeric(combined[i-1,14:18])
  # combined$p_p3[i] = p3 # No beetle impact
  # combined$p_p4[i] = p4 # No beetle impact
  
  pine = whitePine_matrix_model(fertility = pine_fert,
                                survival = pine_surv,
                                growth = pine_growth,
                                time=2,
                                initial_pop = ntrees_0)
  
  pine_pop = pine[[1]]
  combined[i,14:18] = pine_pop[,2]
  combined[i,19] = sum(combined[i,14:18])
  
  frst_crbn = pine[[4]]
  combined[i,20] = frst_crbn[2]
  
  pine_biomass = pine[[3]] # Pull out biomass across stages
  combined$burnt_biomass[i] = ifelse(combined$fire_occurs[i] == "Y" && 
                                    combined$fire_sev[i] == "Low", (sum(pine_biomass[1:3,2])*.3),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Mod", (sum(pine_biomass[1:4,2])*.51),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Sev", (sum(pine_biomass[1:5,2])*.8),
                      0)))
  combined$post_fire_carbon[i] = combined$forest_carbon[i] - (combined$burnt_biomass[i] * 0.47)
}

mod_climate = combined$forest_carbon
mod_climate_fire = combined$post_fire_carbon #to plot with others

```

# Only effected by beetles
```{r beetle}

years = 91
r_0 = 1.16
btl_pop_0 = 5000
ntrees_0 = 1000
time = 2
K_0 = 100000

beetle_parms = list(p0=btl_pop_0, r=r_0, K=K_0)

clim_coef = 1 # Equal to one becuase no climate impact here

pine_fert = c(F0,F1,F2,F3,F4)
pine_growth = c(g01,g12,g23,g34)
pine_surv = c(p0,p1,p2,p3,p4)

combined = data.frame(year = 2010:2100,
                      btl_r_coef = ifelse((log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)<1,1,
                                          (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)),
                      btl_r = rep(NA,91),
                      btl_pop = rep(NA,91),
                      p_p0 = c(p0*clim_coef), # Climate impact
                      p_p1 = rep(p1, 91),
                      p_p2 = rep(p2, 91),
                      p_p3 = rep(NA, 91), # Beetle impact (in for loop)
                      p_p4 = rep(NA, 91), # Beetle impact (in for loop) 
                      g01 = c(g01*clim_coef), # Climate impact
                      g12 = c(g12*clim_coef), # Climate impact
                      g23 = c(g23*clim_coef), # Climate impact
                      g34 = c(g34*clim_coef), # Climate impact
                      pine0 = rep(NA,91),
                      pine1 = rep(NA,91),
                      pine2 = rep(NA,91), 
                      pine3 = rep(NA,91), 
                      pine4 = rep(NA,91),
                      total_pine = rep(0,91),
                      forest_carbon = rep(0,91),
                      fire_prob = rep(NA,91), # Fire probability, binary (High/Low)
                      fire_sev = rep(NA,91), # Fire severity, (Low, Moderate, Severe)
                      fire_occurs = rep(NA,91), # Fire occurs, binary (Y/N)
                      burnt_biomass = rep(0,91), # Total biomass burnt
                      post_fire_carbon = rep(0,91)) # Total forest carbon, post-fire)

combined[,3] = round(r_0*combined$btl_r_coef,2)
combined[1,4] = btl_pop_0
combined[1,5:9] = pine_surv
combined[1,14:18] = c(107,77,300,14,1)
combined[1,19] = sum(combined[1,14:18])
combined[1,20] = 256876
combined[1,21] = ifelse(clim_BAU$Su_tmax[1] >36 && clim_BAU$W_tmin[1] > 2, "H", "L") 
combined[1,22] = ifelse(clim_BAU$apr_snow[1] >=80, "Low", ifelse(clim_BAU$apr_snow[1] >=60, "Mod", "Sev")) 
combined[1,23] = ifelse(combined$fire_prob[1] == "H" && combined$fire_sev[1] == "Mod" |
                          combined$fire_sev[1] == "Sev", "Y", "N")
combined[1,24] = 0 
combined[1,25] = 256876

for(i in 2:years){
################################################# Fire ######################
combined$fire_prob[i] = ifelse(clim_BAU$Su_tmax[i] >36 && clim_BAU$W_tmin[i] > 2, "H", "L")
combined$fire_sev[i] =  ifelse(clim_BAU$apr_snow[i] >=80, "Low", ifelse(clim_BAU$apr_snow[i] >=60, "Mod", "Sev"))
combined$fire_occurs[i] = ifelse(combined$fire_prob[i] == "H" && combined$fire_sev[i] == "Mod"
                                 |combined$fire_sev[i] == "Sev", "Y", "N")

################################################# Beetles ######################

  tmp = data.frame(time = 1:time)
  tmp_result = ode(combined$btl_pop[i-1], tmp$time, beetle_pop, beetle_parms)
  combined$btl_pop[i] = clim_coef * tmp_result[2,2]

################################################# Pines ######################
  
  pine_surv = as.numeric(combined[i-1,5:9])
  pine_growth = as.numeric(combined[i-1,10:13])
  init_pop = as.numeric(combined[i-1,14:18])
  combined$p_p3[i] = combined$p_p3[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  combined$p_p4[i] = combined$p_p4[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  
  pine = whitePine_matrix_model(fertility = pine_fert,
                                survival = pine_surv,
                                growth = pine_growth,
                                time = 2,
                                initial_pop = ntrees_0)
  
  pine_pop = pine[[1]]
  combined[i,14:18] = pine_pop[,2]
  combined[i,19] = sum(combined[i,14:18])
  
  frst_crbn = pine[[4]]
  combined[i,20] = frst_crbn[2]
  
  pine_biomass = pine[[3]] # Pull out biomass across stages
  combined$burnt_biomass[i] = ifelse(combined$fire_occurs[i] == "Y" && 
                                    combined$fire_sev[i] == "Low", (sum(pine_biomass[1:3,2])*.3),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Mod", (sum(pine_biomass[1:4,2])*.51),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Sev", (sum(pine_biomass[1:5,2])*.8),
                      0)))
  combined$post_fire_carbon[i] = combined$forest_carbon[i] - (combined$burnt_biomass[i] * 0.47)
}

mod_beetle = combined$forest_carbon
mod_beetle_fire = combined$post_fire_carbon #to plot with others

```

# Effected by both
```{r climate_beetle}
clim_coef = clim_moderate$cwd[1]/clim_moderate$cwd
pine_surv = c(p0,p1,p2,p3,p4)

combined = data.frame(year = 2010:2100,
                      btl_r_coef = ifelse((log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)<1,1,
                                          (log(sqrt(abs(clim_BAU$W_tmin[1]-clim_BAU$W_tmin)),10)+1)),
                      btl_r = rep(NA,91),
                      btl_pop = rep(NA,91),
                      p_p0 = c(p0*clim_coef), # Climate impact
                      p_p1 = rep(p1, 91),
                      p_p2 = rep(p2, 91),
                      p_p3 = rep(NA, 91), # Beetle impact (in for loop)
                      p_p4 = rep(NA, 91), # Beetle impact (in for loop) 
                      g01 = c(g01*clim_coef), # Climate impact
                      g12 = c(g12*clim_coef), # Climate impact
                      g23 = c(g23*clim_coef), # Climate impact
                      g34 = c(g34*clim_coef), # Climate impact
                      pine0 = rep(NA,91),
                      pine1 = rep(NA,91),
                      pine2 = rep(NA,91), 
                      pine3 = rep(NA,91), 
                      pine4 = rep(NA,91),
                      total_pine = rep(NA,91),
                      forest_carbon = rep(NA,91),
                      fire_prob = rep(NA,91), # Fire probability, binary (High/Low)
                      fire_sev = rep(NA,91), # Fire severity, (Low, Moderate, Severe)
                      fire_occurs = rep(NA,91), # Fire occurs, binary (Y/N)
                      burnt_biomass = rep(0,91), # Total biomass burnt
                      post_fire_carbon = rep(0,91)) # Total forest carbon, post-fire)

combined[,3] = round(r_0*combined$btl_r_coef,2)
combined[1,4] = btl_pop_0
combined[1,5:9] = pine_surv
combined[1,14:18] = c(107,77,300,14,1)
combined[1,19] = sum(combined[1,14:18])
combined[1,20] = 256876
combined[1,21] = ifelse(clim_BAU$Su_tmax[1] >36 && clim_BAU$W_tmin[1] > 2, "H", "L") 
combined[1,22] = ifelse(clim_BAU$apr_snow[1] >=80, "Low", ifelse(clim_BAU$apr_snow[1] >=60, "Mod", "Sev")) 
combined[1,23] = ifelse(combined$fire_prob[1] == "H" && combined$fire_sev[1] == "Mod" |
                          combined$fire_sev[1] == "Sev", "Y", "N")
combined[1,24] = 0 
combined[1,25] = 256876

for(i in 2:years){
################################################# Fire ######################
combined$fire_prob[i] = ifelse(clim_BAU$Su_tmax[i] >36 && clim_BAU$W_tmin[i] > 2, "H", "L")
combined$fire_sev[i] =  ifelse(clim_BAU$apr_snow[i] >=80, "Low", ifelse(clim_BAU$apr_snow[i] >=60, "Mod", "Sev"))
combined$fire_occurs[i] = ifelse(combined$fire_prob[i] == "H" && combined$fire_sev[i] == "Mod"
                                 |combined$fire_sev[i] == "Sev", "Y", "N")

################################################# Beetles ######################

  tmp = data.frame(time = 1:time)
  tmp_result = ode(combined$btl_pop[i-1], tmp$time, beetle_pop, beetle_parms)
  combined$btl_pop[i] = clim_coef[i] * tmp_result[2,2]

################################################# Pines ######################
  
  # Pines
  pine_surv = as.numeric(combined[i-1,5:9])
  pine_growth = as.numeric(combined[i-1,10:13])
  init_pop = as.numeric(combined[i-1,14:18])
  combined$p_p3[i] = combined$p_p3[1]*log(sqrt(combined$btl_pop[1]))/log(sqrt(combined$btl_pop[i]))
  combined$p_p4[i] = combined$p_p4[1]*log(combined$btl_pop[1])/log(combined$btl_pop[i])
  
  pine = whitePine_matrix_model(fertility = pine_fert,
                                survival = pine_surv,
                                growth = pine_growth,
                                time=2,
                                initial_pop = ntrees_0)
  
  pine_pop = pine[[1]]
  combined[i,14:18] = pine_pop[,2]
  combined[i,19] = sum(combined[i,14:18])
  
  frst_crbn = pine[[4]]
  combined[i,20] = frst_crbn[2]
  
  pine_biomass = pine[[3]] # Pull out biomass across stages
  combined$burnt_biomass[i] = ifelse(combined$fire_occurs[i] == "Y" && 
                                    combined$fire_sev[i] == "Low", (sum(pine_biomass[1:3,2])*.3),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Mod", (sum(pine_biomass[1:4,2])*.51),
                  ifelse(combined$fire_occurs[i] == "Y" && combined$fire_sev[i] == "Sev", (sum(pine_biomass[1:5,2])*.8),
                      0)))
  combined$post_fire_carbon[i] = combined$forest_carbon[i] - (combined$burnt_biomass[i] * 0.47)
}

mod_climate_and_beetle = combined$forest_carbon
mod_climate_and_beetle_fire = combined$post_fire_carbon #to plot with others

```

# Trends
```{r output_vis}
mod_forest_carbon_df = cbind.data.frame(year = 2010:2100,
                                        beetle=beetle,
                                        climate=climate,
                                        climate_and_beetle=climate_and_beetle,
                                        beetle_fire,
                                        climate_fire,
                                        climate_and_beetle_fire) %>% 
 # filter(year != "2010"&year !="2011") %>% # weird things happening in these years. Excluding because not important to trends
   melt(1)

colnames(mod_forest_carbon_df) = c("year","scenario","carbon")

moderate_trends = ggplot(mod_forest_carbon_df,aes(x=year,y=carbon))+
  geom_line(aes(color=scenario))

bau_trends
moderate_trends
```


