---
title: "ForestCarbonSeq"
author: "Claire Powers"
date: "5/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```

### Pulling submodels together

####Beetle: Logistic model
```{r}
source("../R/SubModel1_BarkBeetles.R")

t=100

beetles = as.data.frame(matrix(nrow = t,ncol = 2))
colnames(beetles) = c("time","pop")
beetles[,1] = seq(1:t)

r = 0.3
K = 10000
N_0 = 500

for(i in 2:t){
  beetles[1,2] = N_0
  beetles[i,2] = beetle_pop(beetles$pop[i-1],r=r,K=K)
}

plot(beetles$time,beetles$pop)
```

####Climate dataframes
```{r}

#temp_BAU = increase of 10 degrees over 80 yrs
#temp <0C = pine beetle babies killed

BAU_temp_summer = rnorm(n = 80, mean = 80, sd = 5)
BAU_temp_winter = rnorm(n = 80, mean = 35, sd = 5)
BAU_precip = rnorm(n = 80, mean = 20, sd = 5)

climate_array <- cbind.data.frame(BAU_precip, BAU_temp_summer, BAU_temp_winter)

```


####Pine: Growth... model
```{r}

source("../R/SubModel2_Pines.R")

initialpop <- c(100, 50, 25, 15, 10)

F1 = 0
F2 = 0.5
F3 = 0.6
F4 = 0.4
F5 = 0

S1 = 0.5
S2 = 0.4
S3 = 0.4
S4 = 0.3
S5 = 0

#climate_array$coeff_summerT <- with(climate_array, ifelse(BAU_temp_summer >80, .2, 0)) 

fertility_BAU <- c(F1, F2, F3, F4, F5)
survivability_BAU <- c(S1, S2, S3, S4, S5)

fertility_3W <- c(F1, F2-.2, F3-.3, F4-.2, F5)
survivability_3W <- c(S1 - .2, S2, S3, S4, S5)

fertility_6W <- c(F1, F2-.3, F3-.3, F4, F5)
survivability_6W <- c(S1 - .3, S2, S3, S4, S5)

nstep <- 10

pine_pop_BAU <- pine_pop(fertility = fertility_BAU, survivability = survivability_BAU, 
                      initialpop = initialpop, nstep = nstep)

pine_pop_3W <- pine_pop(fertility = fertility_3W, survivability = survivability_3W, 
                      initialpop = initialpop, nstep = nstep)

pine_pop_3W <- pine_pop(fertility = fertility_6W, survivability = survivability_6W, 
                      initialpop = initialpop, nstep = nstep)

#pine_pop <- pine_pop(fertility = if)
  
  
#Arrange data (short and long)
year_pine = seq(from=1, to=nstep)
pine_ages = cbind.data.frame(year=year_pine, t(pine_pop$pop_by_age))
pine_ages_long = pine_ages %>% gather(key="age_class", value="pop",-year)

#Graph
ggplot(pine_ages_long, aes(x = year, y = pop, fill = age_class))+
  geom_col()

```

####Climate dataframes
```{r}

#temp_BAU = increase of 10 degrees over 80 yrs
#temp <0C = pine beetle babies killed

BAU_temp_summer = rnorm(n = 80, mean = 80, sd = 5)
BAU_temp_winter = rnorm(n = 80, mean = 35, sd = 5)
BAU_precip_BAU = rnorm(n = 80, mean = 20, sd = 5)

```


