---
title: "SubModel2 - White Pine Growth"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages_and_function, message=FALSE}
library(tidyverse)
library(sensitivity)
library(reshape2)
library(cowplot)
source("../R/SubModel2_PineModel.R")

options(scipen = 999)
```


```{r model_input_setup, message=FALSE}
# Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742 
F3 = 0.2536 
F4 = 1.6902 

# Survival
p0 = 0.9353 
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959

# Growth
g01 = 0.0018
g12 = 0.0104
g23 = 0.0144
g34 = 0.0144

# Initial Population: Assume that we start with 10 adult rabbits.
P0 = c(100,100,100,100,100)

# Time
years = 91

# Fertility vector to put into matrix
pine_fert = c(F0,F1,F2,F3,F4)

# Survival vector to put into matrix
pine_surv = c(p0,p1,p2,p3,p4)

# Growth vector to put into matrix
pine_growth = c(g01,g12,g23,g34)

stages = c("ht<1.37","0.1to10cm","10.1to20cm","20.1to40cm",">40cm")
```


```{r model_use_no_hawks}
# Run model
pine_baseline = whitePine_matrix_model(fertility = pine_fert,
                                        survival = pine_surv,
                                        growth=pine_growth,
                                        initial_pop = P0,
                                        time=years)

carbon_seq = pine_baseline[[4]]
```

Just climate change
```{r}
# Fecundity
F0 = 0 
F1 = 0 
F2 = 0.0742 
F3 = 0.2536 
F4 = 1.6902 

# Survival
p0 = 0.7353 
p1 = 0.9827
p2 = 0.9720
p3 = 0.9806
p4 = 0.9959

# Growth
g01 = 0.0018/2
g12 = 0.0104/2
g23 = 0.0144/2
g34 = 0.0144/2

# Initial Population: Assume that we start with 10 adult rabbits.
P0 = c(100,100,100,100,100)

# Time
years = 91

# Fertility vector to put into matrix
pine_fert = c(F0,F1,F2,F3,F4)

# Survival vector to put into matrix
pine_surv = c(p0,p1,p2,p3,p4)

# Growth vector to put into matrix
pine_growth = c(g01,g12,g23,g34)

stages = c("ht<1.37","0.1to10cm","10.1to20cm","20.1to40cm",">40cm")
```


```{r}
pine_cc = whitePine_matrix_model(fertility = pine_fert,
                                        survival = pine_surv,
                                        growth=pine_growth,
                                        initial_pop = P0,
                                        time=years)

carbon_seq2 = pine_cc[[4]]

cbind(carbon_seq,carbon_seq2)
```





